<?php
// Add Some Code Here for design
?>
<span> Product Range Search </span>

<form id="my-form" method="POST" action="<?= $this->getUrl('productrange/form/ajax'); ?>" role="form" name="RegForm" enctype="multipart/form-data">
    <fieldset class="fieldset">
        <div class="field low required">
            <label class="label" for="low"><span><?= $block->escapeHtml(__('Low')) ?></span></label>
            <div class="control">
                <input name="low" id="low" title="Low" value="" class="input-text" type="text" data-validate='{"required":true, "validate-zero-or-greater":true }'/>
            </div>
        </div>
        <div class="field low required">
            <label class="label" for="high"><span><?= $block->escapeHtml(__('High')) ?></span></label>
            <div class="control">
                <input name="high" id="high" title="High" value="" class="input-text" type="text" data-validate='{"required":true, "high-multiple-5x": true}'/>
            </div>
        </div>
        <div class="field sort required">
            <label for="sort" class="label"><span><?= $block->escapeHtml(__('Sort')) ?></span></label>
            <div class="control">
                <select id="sort" name="sort" title="<?= $block->escapeHtmlAttr(__('Sort')) ?>" class="select">
                    <option selected="selected" value="asc"><?= $block->escapeHtml(__('Ascending')) ?></option>
                    <option value="desc"><?= $block->escapeHtml(__('Descending')) ?></option>
                </select>
            </div>
        </div>
    </fieldset>
    <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>"/>
    <div class="primary">
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="Submit" id="range-submit-btn" class="action submit primary" data-mage-init='{"product_range":{}}'>
                    <span>Submit</span>
                </button>
            </div>
        </div>
    </div>
</form>


<script type="text/javascript">
    require([
        'jquery',
        'mage/mage',
        'mage/validation'
    ], function($){
        var contact_form = jQuery('#my-form');
        contact_form.mage('validation', {});
    });
</script>